### ISSUE TITLE
small variable mismatch within controls.js:playTrackByUri() function ?

### ISSUE THREAD

**Issue by Diru** [pimusicbox/mopidy-musicbox-webclient#122]
It looks like line 153 needs to be be:

func = mopidy.tracklist.add(null, null, **track_uri**);

**Comment by kingosticks** [comment]
No, that is intentionally trying to add all the playlist's tracks in one call. Some backends support this, some do not. Those that do not are handled by the code following line 153.

**Comment by Diru** [comment]
Clicking on a "songLi" result via the search page returns an error for me in the console without that change. I only installed the extension 15 minutes ago so I may be doing something wrong.

**Comment by kingosticks** [comment]
An error in the console and the tracks are also not added? Or just an
error? I've got a new version of that code which makes use of Mopidy's v1.x
API so I'll get that committed.

**Comment by Diru** [comment]
I'm using Mopidy version 1.1.0 and just the error below happens on clicking a search result.

```
Server returned error: Object {message: "Application error", code: 0, data: Object}code: 0data: Objectmessage: "Expected a valid URI, not u'trackresultscache'"traceback: "Traceback (most recent call last):↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 133, in _handle_single_request↵    result = self._unwrap_result(result)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/jsonrpc.py", line 222, in _unwrap_result↵    result = result.get()↵  File "/usr/local/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get↵    compat.reraise(*self._data['exc_info'])↵  File "/usr/local/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise↵    exec('raise tp, value, tb')↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop↵    response = self._handle_receive(message)↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive↵    return callee(*message['args'], **message['kwargs'])↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/core/tracklist.py", line 415, in add↵    uri is None or validation.check_uri(uri)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/validation.py", line 100, in check_uri↵    raise exceptions.ValidationError(msg.format(arg=arg))↵ValidationError: Expected a valid URI, not u'trackresultscache'↵"type: "ValidationError"__proto__: Objectmessage: "Application error"__proto__: Object
Potentially unhandled rejection [1] ServerError: Application error

```

**Comment by kingosticks** [comment]
Ahh Yeh ok that one is fixed in develop branch. Need to do a release.
